import "./InspectionReport.css";
import DownloadReportButton from "./DownloadReportButton";

function InspectionReport({ analysis, detections, imageUrl }) {
    
    if (!analysis) return null;

    return (

<div className="inspection-report">

    <h2 className="report-title">
        📋 PCB Inspection Report
    </h2>

    <div className="report-header">

        <div className="report-item">
            <span>Inspection ID</span>
            <strong>{analysis.inspection_id}</strong>
        </div>

        <div className="report-item">
            <span>Generated On</span>
            <strong>{analysis.timestamp}</strong>
        </div>

        <div className="report-item">
            <span>Status</span>
            <strong>{analysis.inspection_status}</strong>
        </div>

        <div className="report-item">
            <span>Model</span>
            <strong>YOLOv8</strong>
        </div>

    </div>
            
            
    <div className="report-section">

        <h3>Summary</h3>

        <div className="summary-grid">

            <div className="summary-box">

                <span>Total Defects</span>

                <strong>{analysis.total_defects}</strong>

            </div>

            <div className="summary-box">

                <span>Highest Confidence</span>

                <strong>{analysis.highest_confidence}%</strong>
            </div>

            <div className="summary-box">

                <span>Average Confidence</span>

                <strong>{analysis.average_confidence}%</strong>
            </div>

            <div className="summary-box">

                <span>Most Common Defect</span>

                <strong>
                {Object.keys(analysis.distribution)[0]}
                </strong>

            </div>
        </div>
                
        <div className="report-section">

        <h3>AI Recommendation</h3>

            <div className={`recommendation-card ${analysis.inspection_status.toLowerCase().replace(" ", "-")}`}>

            <h4>{analysis.inspection_status}</h4>

            <p>{analysis.recommendation}</p>

            </div>

        </div>

            
        <div className="report-section">

            <h3>Inspection Observations</h3>

            <ul className="observation-list">
                {analysis.observations.map((item, index) => (
                <li key={index}>
                ✓ {item}
                </li>
                ))}
            </ul>

        </div>


        <div className="report-footer">

            <p>
                <strong>Model:</strong> YOLOv8
            </p>

            <p>
                <strong>Generated By:</strong> AI Powered PCB Defect Detection System
            </p>

            <p>
                <strong>Report ID:</strong> {analysis.inspection_id}
            </p>

            <p>
             © 2026
            </p>

            </div> 
                
        <div className="report-download">

            <DownloadReportButton
            analysis={analysis}
            detections={detections}
            imageUrl={imageUrl}
            />
        </div>


</div>

</div>

    );

}

export default InspectionReport;